// Generated by scripts/optimize-design-demos.mjs
// Model: qwen3:8b via local Ollama
// Executed examples: 2
// Full corpus available in scripts/design-training-set.mjs

export const optimizedDesignDemos = [
  {
    "traces": [
      {
        "source": "generated",
        "designBrief": "Create a 2-of-3 family recovery policy with Alice, Bob, and Carol.",
        "policy": "thresh(2,pk(Alice),pk(Bob),pk(Carol))",
        "explanation": "This requires any two of the three keys. It is the standard compact expression for a family recovery quorum.",
        "cautions": [
          "All keys should be distinct and backed up independently."
        ]
      }
    ],
    "programId": "design"
  }
]
