// Generated by scripts/optimize-design-demos.mjs
// Model: qwen2.5:1.5b via local Ollama
// Executed train examples: 48
// Held-out eval examples: 32
// Full corpus summary: data/corpus/summary.json

export const optimizedDesignDemos = [
  {
    "traces": [
      {
        "designBrief": "A wallet requiring two out of six specific keys for spending.",
        "policy": "thresh(2, pk(key_1), pk(key_2), pk(key_3), pk(key_4), pk(key_5), pk(key_6))"
      },
      {
        "designBrief": "A corporation wants to enhance the security of its cryptocurrency treasury. To prevent unauthorized access and ensure corporate governance, the corporation decides to implement a multi-signature wallet where three corporate officers must agree to execute a transaction",
        "policy": "thresh(3,pk(officer_1),pk(officer_2),pk(officer_3))"
      },
      {
        "designBrief": "A wallet with 4 keys where you need all 4 keys to spend the funds.",
        "policy": "thresh(4,pk(key_1),pk(key_2),pk(key_3),pk(key_4))"
      },
      {
        "designBrief": "The following miniscript policy does not compile:\nor(and(pk(A),pk(B)),and(pk(A),pk(C)))\n\nPropose a corrected policy and explain what caused the error and how the corrected policy addresses it.",
        "policy": "or(and(pk(A),pk(B)),pk(C))"
      },
      {
        "designBrief": "A contest with a Bitcoin prize that's open to a select few participants (say, 6 participants). The first to solve an elaborate puzzle set up by the organizer can claim the prize.",
        "policy": "thresh(6,pk(participant_1),pk(participant_2),pk(participant_3),pk(participant_4),pk(participant_5),pk(participant_6))"
      },
      {
        "designBrief": "Design a script policy requiring any two out of seven specified keys for spending.",
        "policy": "thresh(2, pk(key_1), pk(key_2), pk(key_3), pk(key_4), pk(key_5), pk(key_6), pk(key_7))"
      }
    ],
    "programId": "design"
  }
]
